# config.yml

backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
collections:
  - name: "config"
    label: "Config"
    editor:
      preview: false
    files:
      - label: "Organizations"
        name: "organizations"
        file: "_data/organizations.yml"
        fields:
          - label: "Organization Items"
            name: "items"
            widget: "list"
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Country, name: country, widget: string}
              - {label: Website, name: website, widget: string, required: false}
              - {label: Logo, name: logo, widget: image}
              - {label: Featured, name: featured, widget: boolean}
              - {label: Actions EN, name: actions_en, widget: string, required: false}
              - {label: Actions ES, name: actions_es, widget: string, required: false}
              - {label: Actions PT, name: actions_pt, widget: string, required: false}
      - label: "Events"
        name: "events"
        file: "_data/events.yml"
        fields:
          - label: "Event Items"
            name: "items"
            widget: "list"
            fields:
              - {label: "Title EN", name: title_en, widget: string}
              - {label: "Title PT", name: title_pt, widget: string}
              - {label: "Title ES", name: title_es, widget: string}
              - {label: "Content EN", name: content_en, widget: text}
              - {label: "Content ES", name: content_es, widget: text}
              - {label: "Content PT", name: content_pt, widget: text}
              - {label: "Image", name: image, widget: image}
              - {label: "Datetime (UTC)", name: datetime, widget: datetime, picker_utc: true}
              - {label: "Active", name: active, widget: boolean}
              - {label: "Registration link", name: registration_link, widget: string}
      - label: "Authorities"
        name: "authorities"
        file: "_data/authorities.yml"
        fields:
          - label: "Authorities Items"
            name: "items"
            widget: "list"
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Position, name: position, widget: string}
              - {label: Country, name: country, widget: string}
              - {label: Party, name: party, widget: string}